import { Inter, League_Spartan, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/UI/Navbar";
import Footer from "@/components/UI/Footer";

const primaryFont = Space_Grotesk({
  variable: "--font-primary",
  subsets: ["latin"],
});

const secondaryFont = Inter({
  variable: "--font-secondary",
  subsets: ["latin"],
});

const logoFont = League_Spartan({
    variable: "--font-title",
    subsets: ["latin"]
})

/* const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${primaryFont.variable} ${secondaryFont.variable} ${logoFont.variable}`} /* geistSans.variable */
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
